const data = {
  "lakeLevel": "171.63ft 5:45pm",
  "currentWeather": {
    "temp": 78.69,
    "feels_like": 80.17,
    "description": "overcast clouds",
    "wind_speed": 9.19,
    "wind_deg": 150,
    "gust": 15.59,
    "sunrise": "06:10 AM",
    "sunset": "08:19 PM",
    "dayOrNight": "day",
    "humidity": 83,
    "uv_index": 0.23,
    "pressure": 1015,
    "moon_phase": 0.64,
    "visibility": 10000,
    "dew_point": 73.09
  },
  "fiveDayWeather": [
    {
      "date": "Monday",
      "high": 90.09,
      "low": 73.18,
      "description": "moderate rain",
      "wind_speed": 9.42,
      "wind_deg": 200,
      "gust": 24.11,
      "humidity": 64,
      "uv_index": 10.6,
      "pressure": 1015,
      "moon_phase": 0.68,
      "dew_point": 72.45,
      "visibility": 10000
    },
    {
      "date": "Tuesday",
      "high": 93.97,
      "low": 74.08,
      "description": "scattered clouds",
      "wind_speed": 12.28,
      "wind_deg": 189,
      "gust": 26.96,
      "humidity": 49,
      "uv_index": 11.39,
      "pressure": 1014,
      "moon_phase": 0.71,
      "dew_point": 69.37,
      "visibility": 10000
    },
    {
      "date": "Wednesday",
      "high": 90.95,
      "low": 74.23,
      "description": "clear sky",
      "wind_speed": 13.8,
      "wind_deg": 183,
      "gust": 26.26,
      "humidity": 50,
      "uv_index": 11.43,
      "pressure": 1014,
      "moon_phase": 0.75,
      "dew_point": 70.05,
      "visibility": "Unavailable"
    },
    {
      "date": "Thursday",
      "high": 91.81,
      "low": 73.6,
      "description": "light rain",
      "wind_speed": 6.17,
      "wind_deg": 186,
      "gust": 21.47,
      "humidity": 51,
      "uv_index": 10.36,
      "pressure": 1019,
      "moon_phase": 0.78,
      "dew_point": 69.69,
      "visibility": "Unavailable"
    },
    {
      "date": "Friday",
      "high": 89.96,
      "low": 71.19,
      "description": "light rain",
      "wind_speed": 9.98,
      "wind_deg": 132,
      "gust": 20.67,
      "humidity": 52,
      "uv_index": 0.2,
      "pressure": 1019,
      "moon_phase": 0.82,
      "dew_point": 70.21,
      "visibility": "Unavailable"
    }
  ],
  "weatherAlerts": [],
  "barometricPressureHistory": [
    1015,
    1015,
    1015,
    1016,
    1016,
    1016
  ],
  "fishingReport": {
    "date": "Jun 11, 2025",
    "report": "GOOD. Water stained; 81 degrees; 0.61 feet below pool. It is finally summer time, everything around Toledo is getting right, most storms are gone and the sun is cooking. Bass are good. Shallow fish are still strong on frogs, topwaters, swim jigs and wacky-worms from 2-7 feet of water. The deeper bite is coming on strong in 14-18 feet of water with big crankbaits and Carolina rigs. A few great reports of 7 pound bass being caught at night with spinnerbaits, and buzzbaits along the edge of the flooded grass. Crappie are good on brush piles, standing timber, and main lake docks with jigs or live bait. The water temperature is starting to reach the mid to low 80s, pushing crappie out of the creeks. Report by Stephen Johnston, Johnston Fishing."
  }
};