name: Fetch and Deploy Data

on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci # Uses `ci` for faster, reliable installs in CI/CD

      # Step 4: Run fetch script
      - name: Fetch weather and lake data
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node fetch-data.js

      - name: Verify generated files
        run: |
          if [ ! -f data.js ] || [ ! -f fishingReportHistory.json ] || [ ! -f lakeLevelHistory.json ] || [ ! -f barometricPressureHistory.json ]; then
            echo "One or more required files are missing!";
            exit 1;
          fi

      - name: Log generated files
        run: ls -l

      # Step 5: Commit and push updated data
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -f data.js # Force add ignored file
          git add -f data.js fishingReportHistory.json lakeLevelHistory.json barometricPressureHistory.json
          git push