name: Fetch and Commit Data

on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run fetch script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node fetch-data.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.js
          git commit -m "Update data.js"
          git push